### PR TITLE
Added targeting for net461 net462, updated nuget.exe fixed NuGetPack.…

### PR DESCRIPTION
**Pull request by ElanHasson**
…ps1 and upgraded Newtonsoft.json

### CODE REVIEW

**Comment by ElanHasson** [comment]
This was my first time targeting multiple frameworks. I think I did it correctly :)

**Comment by ElanHasson** [comment]
Perhaps not based on the failed build :( 

Let me know what needs fixing.

**Comment by Thwaitesy** [comment]
Hey, @ElanHasson ill take a look at this over the weekend.

Thanks for the PR.

**Comment by iangavr** [comment]
Hi! Are there any updates on this PR?
Currently have an issue similar to [this one](https://github.com/Thwaitesy/MSTestHacks/issues/11) with some of the other packages requiring Newtonsoft.Json >=9.0.0.0

**Comment by ElanHasson** [comment]
I switched the NUnit and haven't looked back.

**Pull request closed without merging**
