### PR TITLE
Update to Json version 6.0.8, and set the Specific Version to false

### PR DESCRIPTION
**Pull request by mach22**
I need to use the latest Json version 6.0.8 but I can't as the specific version is true.
So I have added the Specific Version false to the reference and update the packages to Json 6.0.8

### CODE REVIEW

**Comment by Thwaitesy** [comment]
Thanks @mach22

**Comment by mach22** [comment]
I have updates the package, but nuget can't restore it, as from visual studio nuget package manager I can see only the old 2.3.2.0 Version. IS there a latency in the update of the nuget server?

Inviata dal mio Windows Phone
________________________________
Da: Sam Thwaites<mailto:notifications@github.com>
Inviato: ‎17/‎04/‎2015 05:01
A: Thwaitesy/MSTestHacks<mailto:MSTestHacks@noreply.github.com>
Cc: mach22<mailto:mark222@live.it>
Oggetto: Re: [MSTestHacks] Update to Json version 6.0.8, and set the Specific Version to false (#10)

Thanks @mach22

---

**Comment by Thwaitesy** [comment]
I've just taken a look. It seems to be there now?

Let me know if your still having any issues.



On 17 Apr 2015, at 7:09 pm, mach22 <notifications@github.com<mailto:notifications@github.com>> wrote:

I have updates the package, but nuget can't restore it, as from visual studio nuget package manager I can see only the old 2.3.2.0 Version. IS there a latency in the update of the nuget server?

Inviata dal mio Windows Phone
________________________________
Da: Sam Thwaites<mailto:notifications@github.com>
Inviato: ?17/?04/?2015 05:01
A: Thwaitesy/MSTestHacks<mailto:MSTestHacks@noreply.github.com>
Cc: mach22<mailto:mark222@live.it>
Oggetto: Re: [MSTestHacks] Update to Json version 6.0.8, and set the Specific Version to false (#10)

Thanks @mach22

---
Reply to this email directly or view it on GitHub:
https://github.com/Thwaitesy/MSTestHacks/pull/10#issuecomment-93883253

-

**Comment by mach22** [comment]
I can't download it, if I make a new project and try to ad this reference I can see only the older one.

Inviata dal mio Windows Phone
________________________________
Da: Sam Thwaites<mailto:notifications@github.com>
Inviato: ‎17/‎04/‎2015 11:22
A: Thwaitesy/MSTestHacks<mailto:MSTestHacks@noreply.github.com>
Cc: mach22<mailto:mark222@live.it>
Oggetto: Re: [MSTestHacks] Update to Json version 6.0.8, and set the Specific Version to false (#10)

I've just taken a look. It seems to be there now?

Let me know if your still having any issues.



On 17 Apr 2015, at 7:09 pm, mach22 <notifications@github.com<mailto:notifications@github.com>> wrote:

I have updates the package, but nuget can't restore it, as from visual studio nuget package manager I can see only the old 2.3.2.0 Version. IS there a latency in the update of the nuget server?

Inviata dal mio Windows Phone
________________________________
Da: Sam Thwaites<mailto:notifications@github.com>
Inviato: ?17/?04/?2015 05:01
A: Thwaitesy/MSTestHacks<mailto:MSTestHacks@noreply.github.com>
Cc: mach22<mailto:mark222@live.it>
Oggetto: Re: [MSTestHacks] Update to Json version 6.0.8, and set the Specific Version to false (#10)

Thanks @mach22

---
Reply to this email directly or view it on GitHub:
https://github.com/Thwaitesy/MSTestHacks/pull/10#issuecomment-93883253

-
Reply to this email directly or view it on GitHub<https://github.com/Thwaitesy/MSTestHacks/pull/10#issuecomment-93948924>.


---

**Pull request merged**
